"""Initial revision

Revision ID: 414400805b53
Revises: 
Create Date: 2023-02-10 17:08:46.465070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '414400805b53'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Achievement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Achievement_id'), 'Achievement', ['id'], unique=False)
    op.create_table('Image',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('blob', sa.LargeBinary(), nullable=True),
    sa.Column('hashid', sa.String(), nullable=True),
    sa.Column('sample', sa.String(), nullable=True),
    sa.Column('project', sa.String(), nullable=True),
    sa.Column('material', sa.String(), nullable=True),
    sa.Column('identifier', sa.String(), nullable=True),
    sa.Column('loadname', sa.String(), nullable=True),
    sa.Column('hole_id', sa.Integer(), nullable=True),
    sa.Column('trayname', sa.String(), nullable=True),
    sa.Column('zoom_level', sa.Float(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('nxtals', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('create_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Image_id'), 'Image', ['id'], unique=False)
    op.create_table('Label',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Label_id'), 'Label', ['id'], unique=False)
    op.create_table('User',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_User_id'), 'User', ['id'], unique=False)
    op.create_table('Labels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('label_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['Image.id'], ),
    sa.ForeignKeyConstraint(['label_id'], ['Label.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Labels_id'), 'Labels', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Labels_id'), table_name='Labels')
    op.drop_table('Labels')
    op.drop_index(op.f('ix_User_id'), table_name='User')
    op.drop_table('User')
    op.drop_index(op.f('ix_Label_id'), table_name='Label')
    op.drop_table('Label')
    op.drop_index(op.f('ix_Image_id'), table_name='Image')
    op.drop_table('Image')
    op.drop_index(op.f('ix_Achievement_id'), table_name='Achievement')
    op.drop_table('Achievement')
    # ### end Alembic commands ###
