version: "3.9"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    command: gunicorn frontend.main:app -b "0.0.0.0:8051" --reload
    environment:
      DASH_DEBUG: true
      DASH_HOT_RELOAD: true
    ports:
      - "8051:8051"
    volumes:
      - ./frontend:/frontend
    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    command: bash -c "
      while !</dev/tcp/db/5432; do sleep 1; done;
      uvicorn api.main:app
      --host 0.0.0.0
      --reload
      "
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api
    depends_on:
      - db
    env_file:
      - ./api/.env

  db:
    image: postgres:11
    volumes:
      - postgis-data:/var/lib/postgresql
    env_file:
      - ./api/.env
    environment:
      # If you need to create multiple database you can add coma separated databases eg gis,data
      - ALLOW_IP_RANGE=0.0.0.0/0
      # Add extensions you need to be enabled by default in the DB. Default are the five specified below
#      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
#      - TZ=America/Denver
#      - PGTZ=America/Denver
    ports:
      - "5432:5432"
    restart: on-failure
    healthcheck:
      test: "exit 0"

  pgbackups:
    image: prodrigestivill/postgres-backup-local
    restart: always
    user: postgres:postgres # Optional: see below
    volumes:
      - /var/opt/pgbackups:/backups
    links:
      - db
    depends_on:
      - db
    env_file:
      - ./api/.env
    environment:
      - POSTGRES_EXTRA_OPTS=-Z6 --schema=public --blobs
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=8080
#  pgadmin:
#    container_name: pgadmin4_container
#    image: dpage/pgadmin4
#    restart: always
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: root
#    ports:
#      - "5050:80"

volumes:
  postgis-data:
